-- AlterTable
ALTER TABLE `Invoice` ADD COLUMN `status` ENUM('DRAFT', 'SENT', 'PAID', 'PARTIALLY_PAID', 'OVERDUE', 'CANCELLED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `ProformaInvoice` ADD COLUMN `status` ENUM('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `Quotation` ADD COLUMN `status` ENUM('OPEN', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'DRAFT', 'CANCELLED') NOT NULL DEFAULT 'OPEN';
